import os
import sys
import json
import logging
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from core.tenant.models import TenantSubmissionConfig
from core.submission.http_adapter import SubmissionResult

# Ensure SharePoint_Agent can be imported
sys.path.append(str(Path(__file__).resolve().parent.parent.parent))
from SharePoint_Agent.sharepoint_agent_module import SharePointAgent

logger = logging.getLogger(__name__)

class SharePointDirectAdapter:
    """
    Direct SharePoint Delivery Adapter using Microsoft Graph API.
    Dynamically creates subfolders and uploads Input PDFs, Output JSONs, and Output Excel files.
    """

    def __init__(self, config: Optional[TenantSubmissionConfig] = None):
        self.config = config or TenantSubmissionConfig()
        self.agent = SharePointAgent()
        
    def dispatch(
        self,
        payload: Dict[str, Any],
        pdf_file_paths: Optional[List[str]] = None,
        additional_file_paths: Optional[List[str]] = None,
        config_override: Optional[TenantSubmissionConfig] = None,
        saved_submission_path: Optional[str] = None,
        extra_metadata: Optional[Dict[str, Any]] = None,
    ) -> SubmissionResult:
        active_config = config_override or self.config

        if not active_config.enabled:
            return SubmissionResult(success=False, error_message="Tenant submission is disabled.")

        start_time = time.time()
        
        # 1. Identify Subject for Folder Name
        subject = "Unknown_Subject"
        if extra_metadata and "subject" in extra_metadata and extra_metadata["subject"]:
            subject = extra_metadata["subject"]
        elif payload and isinstance(payload, dict):
            metadata = payload.get("metadata", {})
            if "subject" in metadata and metadata["subject"]:
                subject = metadata["subject"]
            elif "original_file_name" in payload and payload["original_file_name"]:
                subject = payload["original_file_name"]
        
        # Clean subject to be folder-safe
        safe_subject = "".join([c if c.isalnum() or c in " ._-" else "_" for c in subject]).strip()
        if not safe_subject:
            safe_subject = f"Notice_{int(time.time())}"
            
        base_folder = active_config.sharepoint_base_folder.strip("/")
        
        # Generic .env override based on category
        if extra_metadata and "category" in extra_metadata:
            category_name = extra_metadata["category"].upper()
            env_folder_override = os.getenv(f"SHAREPOINT_FOLDER_{category_name}")
            if env_folder_override:
                base_folder = env_folder_override.strip("/")
                logger.info(f"Dynamic folder routing applied for category '{category_name}': {base_folder}")

        target_folder = f"{base_folder}/{safe_subject}" if base_folder else safe_subject

        logger.info(f"Uploading files to SharePoint native folder: {target_folder}")

        # Override agent config if target_url specifies a different SharePoint site
        if active_config.target_url:
            import urllib.parse
            from dotenv import load_dotenv
            load_dotenv()
            
            raw_url = active_config.target_url
            if raw_url.startswith("${") and raw_url.endswith("}"):
                env_key = raw_url[2:-1]
                target_url = os.getenv(env_key, raw_url)
            else:
                target_url = os.path.expandvars(raw_url)
                
            parsed = urllib.parse.urlparse(target_url)
            if parsed.hostname:
                self.agent.hostname = parsed.hostname
            path_parts = [p for p in parsed.path.split('/') if p]
            if len(path_parts) >= 2 and path_parts[0].lower() == 'sites':
                self.agent.site_name = path_parts[1]


        # Ensure Authentication
        if not self.agent.get_site_and_drive_id():
            return SubmissionResult(
                success=False, 
                error_message="SharePoint Agent failed to authenticate or resolve drive.",
                execution_time_seconds=time.time() - start_time
            )

        # 2. Gather files to upload
        files_to_upload = []
        
        # Original Input PDFs
        if active_config.attachments.include_original_pdfs and pdf_file_paths:
            for p_str in pdf_file_paths:
                p = Path(p_str)
                if p.exists() and p.is_file():
                    files_to_upload.append(p)
                    
        # Add explicitly passed POC outputs (Excel, JSONs generated by POC)
        if additional_file_paths:
            for p_str in additional_file_paths:
                p = Path(p_str)
                if p.exists() and p.is_file():
                    files_to_upload.append(p)
        
        # Add the dynamically generated merged JSON specifically
        if saved_submission_path and Path(saved_submission_path).exists():
            files_to_upload.append(Path(saved_submission_path))
            
        # Remove duplicates
        unique_files = list(set(files_to_upload))
        
        # Ensure we don't upload irrelevant configs like tenant.json, only POC outputs
        final_files = []
        for uf in unique_files:
            lname = uf.name.lower()
            if "package.json" in lname or "tenant.json" in lname or "submission.json" in lname:
                continue
            final_files.append(uf)

        if not final_files:
            return SubmissionResult(
                success=True,
                error_message="No files found to upload.",
                execution_time_seconds=time.time() - start_time
            )

        # 3. Upload files
        success_count = 0
        for local_file in final_files:
            logger.info(f"Uploading to SharePoint: {local_file.name}")
            up_res = self.agent.upload_file(folder_path=target_folder, local_file=local_file)
            if up_res:
                success_count += 1
            else:
                logger.error(f"Failed to upload {local_file.name}")

        success = success_count > 0 and success_count == len(final_files)
        
        return SubmissionResult(
            success=success,
            status_code=200 if success else 500,
            error_message=None if success else f"Uploaded {success_count} out of {len(final_files)} files.",
            execution_time_seconds=time.time() - start_time,
            extra_info={"target_folder": target_folder, "files_uploaded": success_count}
        )
