from pydantic import BaseModel, Field
from typing import Optional

class PlanInformation(BaseModel):
    plan_name: Optional[str] = Field(description="Name of the plan")
    carrier: Optional[str] = Field(description="Carrier Name e.g. Aetna, UHC. Must match template dropdowns if possible.")
    plan_source: Optional[str] = Field(default=None, description="PEO or Source (e.g. ADP, TriNet, Justworks)")
    plan_type: Optional[str] = Field(description="e.g. EPO, HMO, PPO - Based")
    specialty_network: Optional[str] = Field(default=None, description="Specialty network name or status")
    zip_code: Optional[str] = Field(default=None)
    renewal_date: Optional[str] = Field(default=None)
    hdhp: Optional[bool] = Field(default=None, description="High deductible health plan flag")
    open_access: Optional[bool] = Field(default=None, description="Open access plan flag")
    plan_design_notes: Optional[str] = Field(default=None, description="Plan design notes or comments")

class DeductiblesAndCoinsurance(BaseModel):
    individual_deductible: Optional[str] = Field(description="In-Network Individual Deductible amount as string, keep $ and comma")
    family_deductible: Optional[str] = Field(description="In-Network Family Deductible amount as string, keep $ and comma")
    deductible_type: Optional[str] = Field(description="e.g. Embedded - Traditional Style, True Individual Family")
    individual_oop_max: Optional[str] = Field(description="Individual Out Of Pocket Maximum as string, keep $ and comma")
    family_oop_max: Optional[str] = Field(description="Family Out Of Pocket Maximum as string, keep $ and comma")
    family_tier: Optional[str] = Field(default=None, description="Calculated Family Tier multiplier (e.g. 2x, 2.5x, 3x)")
    in_network_coinsurance: Optional[str] = Field(default=None, description="The most frequent coinsurance percentage in the In-Network column")

class OfficeVisits(BaseModel):
    primary_care_copay: Optional[str] = Field(description="Copay amount or string like 'No charge'")
    primary_care_copay_modifier: Optional[str] = Field(description="Modifier like 'After Deductible' or 'Deductible Waived'", default=None)
    primary_care_copay_deductible_status: Optional[str] = Field(description="Extract phrases like 'deductible doesn't apply' or 'no charge'", default=None)
    primary_care_coinsurance: Optional[str] = Field(default=None)
    primary_care_coinsurance_modifier: Optional[str] = Field(default=None)
    primary_care_coinsurance_deductible_status: Optional[str] = Field(default=None)
    specialist_copay: Optional[str] = Field(description="Copay amount or string like 'No charge'")
    specialist_copay_modifier: Optional[str] = Field(description="Modifier like 'After Deductible' or 'Deductible Waived'", default=None)
    specialist_copay_deductible_status: Optional[str] = Field(default=None)
    specialist_coinsurance: Optional[str] = Field(default=None)
    specialist_coinsurance_modifier: Optional[str] = Field(default=None)
    specialist_coinsurance_deductible_status: Optional[str] = Field(default=None)

class HospitalSurgical(BaseModel):
    inpatient_copay: Optional[str] = Field(description="Copay amount")
    inpatient_copay_modifier: Optional[str] = Field(default=None)
    inpatient_copay_deductible_status: Optional[str] = Field(default=None)
    inpatient_coinsurance: Optional[str] = Field(default=None)
    inpatient_coinsurance_modifier: Optional[str] = Field(default=None)
    inpatient_coinsurance_deductible_status: Optional[str] = Field(default=None)
    op_hospital_copay: Optional[str] = Field(default=None)
    op_hospital_copay_modifier: Optional[str] = Field(default=None)
    op_hospital_copay_deductible_status: Optional[str] = Field(default=None)
    op_hospital_coinsurance: Optional[str] = Field(default=None)
    op_hospital_coinsurance_modifier: Optional[str] = Field(default=None)
    op_hospital_coinsurance_deductible_status: Optional[str] = Field(default=None)
    er_copay: Optional[str] = Field(description="Copay amount")
    er_copay_modifier: Optional[str] = Field(default=None)
    er_copay_deductible_status: Optional[str] = Field(default=None)
    er_coinsurance: Optional[str] = Field(default=None)
    er_coinsurance_modifier: Optional[str] = Field(default=None)
    er_coinsurance_deductible_status: Optional[str] = Field(default=None)

class UrgentCareLabsImaging(BaseModel):
    urgent_care_copay: Optional[str] = Field(default=None)
    urgent_care_copay_modifier: Optional[str] = Field(default=None)
    urgent_care_copay_deductible_status: Optional[str] = Field(default=None)
    urgent_care_coinsurance: Optional[str] = Field(default=None)
    urgent_care_coinsurance_modifier: Optional[str] = Field(default=None)
    urgent_care_coinsurance_deductible_status: Optional[str] = Field(default=None)
    lab_services_copay: Optional[str] = Field(default=None)
    lab_services_copay_modifier: Optional[str] = Field(default=None)
    lab_services_copay_deductible_status: Optional[str] = Field(default=None)
    lab_services_coinsurance: Optional[str] = Field(default=None)
    lab_services_coinsurance_modifier: Optional[str] = Field(default=None)
    lab_services_coinsurance_deductible_status: Optional[str] = Field(default=None)
    xray_copay: Optional[str] = Field(default=None)
    xray_copay_modifier: Optional[str] = Field(default=None)
    xray_copay_deductible_status: Optional[str] = Field(default=None)
    xray_coinsurance: Optional[str] = Field(default=None)
    xray_coinsurance_modifier: Optional[str] = Field(default=None)
    xray_coinsurance_deductible_status: Optional[str] = Field(default=None)
    medical_imaging_copay: Optional[str] = Field(default=None)
    medical_imaging_copay_modifier: Optional[str] = Field(default=None)
    medical_imaging_copay_deductible_status: Optional[str] = Field(default=None)
    medical_imaging_coinsurance: Optional[str] = Field(default=None)
    medical_imaging_coinsurance_modifier: Optional[str] = Field(default=None)
    medical_imaging_coinsurance_deductible_status: Optional[str] = Field(default=None)

class Pharmacy(BaseModel):
    pharmacy_deductible: Optional[str] = Field(default=None)
    pharmacy_deductible_modifier: Optional[str] = Field(default=None)
    pharmacy_deductible_deductible_status: Optional[str] = Field(default=None)
    offers_tier_1a_benefit: Optional[bool] = Field(default=None, description="Offers Tier 1A Benefit checkbox flag")
    tier_1_copay: Optional[str] = Field(default=None)
    tier_1_copay_modifier: Optional[str] = Field(default=None)
    tier_1_copay_deductible_status: Optional[str] = Field(default=None)
    tier_1_coinsurance: Optional[str] = Field(default=None)
    tier_1_coinsurance_modifier: Optional[str] = Field(default=None)
    tier_1_coinsurance_deductible_status: Optional[str] = Field(default=None)
    tier_2_copay: Optional[str] = Field(default=None)
    tier_2_copay_modifier: Optional[str] = Field(default=None)
    tier_2_copay_deductible_status: Optional[str] = Field(default=None)
    tier_2_coinsurance: Optional[str] = Field(default=None)
    tier_2_coinsurance_modifier: Optional[str] = Field(default=None)
    tier_2_coinsurance_deductible_status: Optional[str] = Field(default=None)
    tier_3_copay: Optional[str] = Field(default=None)
    tier_3_copay_modifier: Optional[str] = Field(default=None)
    tier_3_copay_deductible_status: Optional[str] = Field(default=None)
    tier_3_coinsurance: Optional[str] = Field(default=None)
    tier_3_coinsurance_modifier: Optional[str] = Field(default=None)
    tier_3_coinsurance_deductible_status: Optional[str] = Field(default=None)
    tier_4_copay: Optional[str] = Field(default=None)
    tier_4_copay_modifier: Optional[str] = Field(default=None)
    tier_4_copay_deductible_status: Optional[str] = Field(default=None)
    tier_4_coinsurance: Optional[str] = Field(default=None)
    tier_4_coinsurance_modifier: Optional[str] = Field(default=None)
    tier_4_coinsurance_deductible_status: Optional[str] = Field(default=None)
    specialty_mirrors_tiers_1_3: Optional[bool] = Field(default=None, description="Specialty mirrors tiers 1-3 checkbox flag")
    tier_5_copay: Optional[str] = Field(default=None)
    tier_5_copay_modifier: Optional[str] = Field(default=None)
    tier_5_copay_deductible_status: Optional[str] = Field(default=None)
    tier_5_coinsurance: Optional[str] = Field(default=None)
    tier_5_coinsurance_modifier: Optional[str] = Field(default=None)
    tier_5_coinsurance_deductible_status: Optional[str] = Field(default=None)
    tier_4_maximum: Optional[str] = Field(default=None, description="Maximum out of pocket cost for Tier 4 prescriptions")
    tier_5_maximum: Optional[str] = Field(default=None, description="Maximum out of pocket cost for Tier 5 prescriptions")
    specialty_rx_description: Optional[str] = Field(default=None, description="Concise specialty cost string using slashes (e.g., '$15/$150/$250').")
    formulary_type: Optional[str] = Field(default=None, description="Advance Control Aetna, Aetna Premier Plus, Aetna Value, RX Other/Unknown")

class OutOfNetwork(BaseModel):
    individual_deductible: Optional[str] = Field(description="OON Deductible", default=None)
    family_deductible: Optional[str] = Field(description="OON Deductible", default=None)
    individual_oop_max: Optional[str] = Field(description="OON OOP Max", default=None)
    family_oop_max: Optional[str] = Field(description="OON OOP Max", default=None)
    out_of_network_coverage: Optional[bool] = Field(default=None, description="Out Of Network Coverage checkbox flag")
    coinsurance: Optional[str] = Field(description="OON Coinsurance", default=None)

class MasterSBCSchema(BaseModel):
    plan_information: PlanInformation = Field(default_factory=PlanInformation)
    deductibles_and_coinsurance: DeductiblesAndCoinsurance = Field(default_factory=DeductiblesAndCoinsurance)
    office_visits: OfficeVisits = Field(default_factory=OfficeVisits)
    hospital_surgical: HospitalSurgical = Field(default_factory=HospitalSurgical)
    urgent_care_labs_imaging: UrgentCareLabsImaging = Field(default_factory=UrgentCareLabsImaging)
    pharmacy: Pharmacy = Field(default_factory=Pharmacy)
    out_of_network: OutOfNetwork = Field(default_factory=OutOfNetwork)
