/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SharepointRouteImport } from './routes/sharepoint'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RpveRouteImport } from './routes/rpve'
import { Route as ResourcingEdgeRouteImport } from './routes/resourcing-edge'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RenewalProcessRouteImport } from './routes/renewal-process'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PayrollExtractorRouteImport } from './routes/payroll-extractor'
import { Route as ParitySetupRouteImport } from './routes/parity-setup'
import { Route as OutlookRouteImport } from './routes/outlook'
import { Route as OrganisationRouteImport } from './routes/organisation'
import { Route as OnedriveRouteImport } from './routes/onedrive'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginMonitorRouteImport } from './routes/login-monitor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ExtractionRouteImport } from './routes/extraction'
import { Route as DriveGpuRouteImport } from './routes/drive-gpu'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as DetectionRouteImport } from './routes/detection'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as CoPilotRouteImport } from './routes/co-pilot'
import { Route as ClassificationRouteImport } from './routes/classification'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SharepointRoute = SharepointRouteImport.update({
  id: '/sharepoint',
  path: '/sharepoint',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RpveRoute = RpveRouteImport.update({
  id: '/rpve',
  path: '/rpve',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcingEdgeRoute = ResourcingEdgeRouteImport.update({
  id: '/resourcing-edge',
  path: '/resourcing-edge',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalProcessRoute = RenewalProcessRouteImport.update({
  id: '/renewal-process',
  path: '/renewal-process',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollExtractorRoute = PayrollExtractorRouteImport.update({
  id: '/payroll-extractor',
  path: '/payroll-extractor',
  getParentRoute: () => rootRouteImport,
} as any)
const ParitySetupRoute = ParitySetupRouteImport.update({
  id: '/parity-setup',
  path: '/parity-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlookRoute = OutlookRouteImport.update({
  id: '/outlook',
  path: '/outlook',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationRoute = OrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const OnedriveRoute = OnedriveRouteImport.update({
  id: '/onedrive',
  path: '/onedrive',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginMonitorRoute = LoginMonitorRouteImport.update({
  id: '/login-monitor',
  path: '/login-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionRoute = ExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveGpuRoute = DriveGpuRouteImport.update({
  id: '/drive-gpu',
  path: '/drive-gpu',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionRoute = DetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const CoPilotRoute = CoPilotRouteImport.update({
  id: '/co-pilot',
  path: '/co-pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificationRoute = ClassificationRouteImport.update({
  id: '/classification',
  path: '/classification',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/classification': typeof ClassificationRoute
  '/co-pilot': typeof CoPilotRoute
  '/configuration': typeof ConfigurationRoute
  '/converter': typeof ConverterRoute
  '/detection': typeof DetectionRoute
  '/drive': typeof DriveRoute
  '/drive-gpu': typeof DriveGpuRoute
  '/extraction': typeof ExtractionRoute
  '/health': typeof HealthRoute
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/login-monitor': typeof LoginMonitorRoute
  '/logs': typeof LogsRoute
  '/onedrive': typeof OnedriveRoute
  '/organisation': typeof OrganisationRoute
  '/outlook': typeof OutlookRoute
  '/parity-setup': typeof ParitySetupRoute
  '/payroll-extractor': typeof PayrollExtractorRoute
  '/pipeline': typeof PipelineRoute
  '/renewal-process': typeof RenewalProcessRoute
  '/reports': typeof ReportsRoute
  '/resourcing-edge': typeof ResourcingEdgeRoute
  '/rpve': typeof RpveRoute
  '/settings': typeof SettingsRoute
  '/sharepoint': typeof SharepointRoute
  '/tenants': typeof TenantsRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/classification': typeof ClassificationRoute
  '/co-pilot': typeof CoPilotRoute
  '/configuration': typeof ConfigurationRoute
  '/converter': typeof ConverterRoute
  '/detection': typeof DetectionRoute
  '/drive': typeof DriveRoute
  '/drive-gpu': typeof DriveGpuRoute
  '/extraction': typeof ExtractionRoute
  '/health': typeof HealthRoute
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/login-monitor': typeof LoginMonitorRoute
  '/logs': typeof LogsRoute
  '/onedrive': typeof OnedriveRoute
  '/organisation': typeof OrganisationRoute
  '/outlook': typeof OutlookRoute
  '/parity-setup': typeof ParitySetupRoute
  '/payroll-extractor': typeof PayrollExtractorRoute
  '/pipeline': typeof PipelineRoute
  '/renewal-process': typeof RenewalProcessRoute
  '/reports': typeof ReportsRoute
  '/resourcing-edge': typeof ResourcingEdgeRoute
  '/rpve': typeof RpveRoute
  '/settings': typeof SettingsRoute
  '/sharepoint': typeof SharepointRoute
  '/tenants': typeof TenantsRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/classification': typeof ClassificationRoute
  '/co-pilot': typeof CoPilotRoute
  '/configuration': typeof ConfigurationRoute
  '/converter': typeof ConverterRoute
  '/detection': typeof DetectionRoute
  '/drive': typeof DriveRoute
  '/drive-gpu': typeof DriveGpuRoute
  '/extraction': typeof ExtractionRoute
  '/health': typeof HealthRoute
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/login-monitor': typeof LoginMonitorRoute
  '/logs': typeof LogsRoute
  '/onedrive': typeof OnedriveRoute
  '/organisation': typeof OrganisationRoute
  '/outlook': typeof OutlookRoute
  '/parity-setup': typeof ParitySetupRoute
  '/payroll-extractor': typeof PayrollExtractorRoute
  '/pipeline': typeof PipelineRoute
  '/renewal-process': typeof RenewalProcessRoute
  '/reports': typeof ReportsRoute
  '/resourcing-edge': typeof ResourcingEdgeRoute
  '/rpve': typeof RpveRoute
  '/settings': typeof SettingsRoute
  '/sharepoint': typeof SharepointRoute
  '/tenants': typeof TenantsRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/access'
    | '/classification'
    | '/co-pilot'
    | '/configuration'
    | '/converter'
    | '/detection'
    | '/drive'
    | '/drive-gpu'
    | '/extraction'
    | '/health'
    | '/invoice'
    | '/login'
    | '/login-monitor'
    | '/logs'
    | '/onedrive'
    | '/organisation'
    | '/outlook'
    | '/parity-setup'
    | '/payroll-extractor'
    | '/pipeline'
    | '/renewal-process'
    | '/reports'
    | '/resourcing-edge'
    | '/rpve'
    | '/settings'
    | '/sharepoint'
    | '/tenants'
    | '/upload'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/access'
    | '/classification'
    | '/co-pilot'
    | '/configuration'
    | '/converter'
    | '/detection'
    | '/drive'
    | '/drive-gpu'
    | '/extraction'
    | '/health'
    | '/invoice'
    | '/login'
    | '/login-monitor'
    | '/logs'
    | '/onedrive'
    | '/organisation'
    | '/outlook'
    | '/parity-setup'
    | '/payroll-extractor'
    | '/pipeline'
    | '/renewal-process'
    | '/reports'
    | '/resourcing-edge'
    | '/rpve'
    | '/settings'
    | '/sharepoint'
    | '/tenants'
    | '/upload'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/access'
    | '/classification'
    | '/co-pilot'
    | '/configuration'
    | '/converter'
    | '/detection'
    | '/drive'
    | '/drive-gpu'
    | '/extraction'
    | '/health'
    | '/invoice'
    | '/login'
    | '/login-monitor'
    | '/logs'
    | '/onedrive'
    | '/organisation'
    | '/outlook'
    | '/parity-setup'
    | '/payroll-extractor'
    | '/pipeline'
    | '/renewal-process'
    | '/reports'
    | '/resourcing-edge'
    | '/rpve'
    | '/settings'
    | '/sharepoint'
    | '/tenants'
    | '/upload'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessRoute: typeof AccessRoute
  ClassificationRoute: typeof ClassificationRoute
  CoPilotRoute: typeof CoPilotRoute
  ConfigurationRoute: typeof ConfigurationRoute
  ConverterRoute: typeof ConverterRoute
  DetectionRoute: typeof DetectionRoute
  DriveRoute: typeof DriveRoute
  DriveGpuRoute: typeof DriveGpuRoute
  ExtractionRoute: typeof ExtractionRoute
  HealthRoute: typeof HealthRoute
  InvoiceRoute: typeof InvoiceRoute
  LoginRoute: typeof LoginRoute
  LoginMonitorRoute: typeof LoginMonitorRoute
  LogsRoute: typeof LogsRoute
  OnedriveRoute: typeof OnedriveRoute
  OrganisationRoute: typeof OrganisationRoute
  OutlookRoute: typeof OutlookRoute
  ParitySetupRoute: typeof ParitySetupRoute
  PayrollExtractorRoute: typeof PayrollExtractorRoute
  PipelineRoute: typeof PipelineRoute
  RenewalProcessRoute: typeof RenewalProcessRoute
  ReportsRoute: typeof ReportsRoute
  ResourcingEdgeRoute: typeof ResourcingEdgeRoute
  RpveRoute: typeof RpveRoute
  SettingsRoute: typeof SettingsRoute
  SharepointRoute: typeof SharepointRoute
  TenantsRoute: typeof TenantsRoute
  UploadRoute: typeof UploadRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharepoint': {
      id: '/sharepoint'
      path: '/sharepoint'
      fullPath: '/sharepoint'
      preLoaderRoute: typeof SharepointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpve': {
      id: '/rpve'
      path: '/rpve'
      fullPath: '/rpve'
      preLoaderRoute: typeof RpveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resourcing-edge': {
      id: '/resourcing-edge'
      path: '/resourcing-edge'
      fullPath: '/resourcing-edge'
      preLoaderRoute: typeof ResourcingEdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewal-process': {
      id: '/renewal-process'
      path: '/renewal-process'
      fullPath: '/renewal-process'
      preLoaderRoute: typeof RenewalProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-extractor': {
      id: '/payroll-extractor'
      path: '/payroll-extractor'
      fullPath: '/payroll-extractor'
      preLoaderRoute: typeof PayrollExtractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parity-setup': {
      id: '/parity-setup'
      path: '/parity-setup'
      fullPath: '/parity-setup'
      preLoaderRoute: typeof ParitySetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlook': {
      id: '/outlook'
      path: '/outlook'
      fullPath: '/outlook'
      preLoaderRoute: typeof OutlookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation': {
      id: '/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof OrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onedrive': {
      id: '/onedrive'
      path: '/onedrive'
      fullPath: '/onedrive'
      preLoaderRoute: typeof OnedriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-monitor': {
      id: '/login-monitor'
      path: '/login-monitor'
      fullPath: '/login-monitor'
      preLoaderRoute: typeof LoginMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extraction': {
      id: '/extraction'
      path: '/extraction'
      fullPath: '/extraction'
      preLoaderRoute: typeof ExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive-gpu': {
      id: '/drive-gpu'
      path: '/drive-gpu'
      fullPath: '/drive-gpu'
      preLoaderRoute: typeof DriveGpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-pilot': {
      id: '/co-pilot'
      path: '/co-pilot'
      fullPath: '/co-pilot'
      preLoaderRoute: typeof CoPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classification': {
      id: '/classification'
      path: '/classification'
      fullPath: '/classification'
      preLoaderRoute: typeof ClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessRoute: AccessRoute,
  ClassificationRoute: ClassificationRoute,
  CoPilotRoute: CoPilotRoute,
  ConfigurationRoute: ConfigurationRoute,
  ConverterRoute: ConverterRoute,
  DetectionRoute: DetectionRoute,
  DriveRoute: DriveRoute,
  DriveGpuRoute: DriveGpuRoute,
  ExtractionRoute: ExtractionRoute,
  HealthRoute: HealthRoute,
  InvoiceRoute: InvoiceRoute,
  LoginRoute: LoginRoute,
  LoginMonitorRoute: LoginMonitorRoute,
  LogsRoute: LogsRoute,
  OnedriveRoute: OnedriveRoute,
  OrganisationRoute: OrganisationRoute,
  OutlookRoute: OutlookRoute,
  ParitySetupRoute: ParitySetupRoute,
  PayrollExtractorRoute: PayrollExtractorRoute,
  PipelineRoute: PipelineRoute,
  RenewalProcessRoute: RenewalProcessRoute,
  ReportsRoute: ReportsRoute,
  ResourcingEdgeRoute: ResourcingEdgeRoute,
  RpveRoute: RpveRoute,
  SettingsRoute: SettingsRoute,
  SharepointRoute: SharepointRoute,
  TenantsRoute: TenantsRoute,
  UploadRoute: UploadRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
